<?php

require_once 'C:\xampp\htdocs\dbcontest\Datacontest.php';

/**
 * Test class for Datacontest.
 * Generated by PHPUnit on 2012-02-28 at 17:10:29.
 */
class DatacontestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Datacontest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Datacontest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('localhost', 'root', "") == true.
     *
     * @covers Datacontest::dbserver
     */
    public function testDbserver()
    {
        $this->assertEquals(
          true,
          $this->object->dbserver('localhost', 'root', "")
        );
    }

    /**
     * Generated from @assert ('myclasstest') == true.
     *
     * @covers Datacontest::db_select_db
     */
    public function testDb_select_db()
    {
        $this->assertEquals(
          true,
          $this->object->db_select_db('myclasstest')
        );
    }

    /**
     * Generated from @assert ('emp_info') == true.
     *
     * @covers Datacontest::select
     */
    public function testSelect()
    {
        $this->assertEquals(
          true,
          $this->object->select('emp_info')
        );
    }
}
?>
